package CM.sandbox;

/*Generated by MPS */

import CM.test.Display;
import CM.test.Loader;
import CM.test.Shader;
import CM.test.Renderer;
import CM.test.RawModel;
import CM.test.ModelLoader;
import CM.test.MTexture;
import CM.test.TModel;
import CM.test.Entity;
import org.lwjgl.util.vector.Vector3f;
import CM.test.Cam;

public class testCake {

  /*package*/ double eggs = 0;
  /*package*/ double flour = 0;
  /*package*/ double sugar = 0;
  /*package*/ double cocoaPowder = 0;
  /*package*/ double milk = 0;
  /*package*/ double butter = 0;
  /*package*/ double vanilla = 0;
  /*package*/ double salt = 0;
  /*package*/ double bakingSoda = 0;
  /*package*/ double foodColoring = 0;




  public void createTier() {

    String bottom = "chocolate";
    String top = "redvelvet";
    double bottomSize = 4;
    double topSize = 1;
    if (bottom.equalsIgnoreCase("chocolate")) {
      createChocolateTier(bottomSize);
    } else if (bottom.equalsIgnoreCase("redvelvet")) {
      createRedVelvetTier(bottomSize);
    }
    if (top.equalsIgnoreCase("chocolate")) {
      createChocolateTier(topSize);
    } else if (top.equalsIgnoreCase("redvelvet")) {
      createRedVelvetTier(topSize);
    }

  }

  public void addToIngredient(double ingredient, double amount) {
    ingredient += amount;
  }

  public void createChocolateTier(double size) {
    this.eggs += Math.round((3 * (size / 10)) * 100) / 100;
    this.cocoaPowder += 3.5 * (size / 10);
    this.sugar += 2 * (size / 10);
    this.vanilla += 1.5 * (size / 10);
    this.bakingSoda += 2 * (size / 10);
    this.flour += 3 * (size / 10);
    this.butter += 1 * (size / 10);
    this.milk += 1;
  }

  public void createRedVelvetTier(double size) {
    this.eggs += Math.round((2 * (size / 10)) * 100) / 100;
    this.cocoaPowder += 3 * (size / 10);
    this.sugar += 1.5 * (size / 10);
    this.foodColoring += 2 * (size / 10);
    this.vanilla += 2 * (size / 10);
    this.salt += 1 * (size / 10);
    this.bakingSoda += 1 * (size / 10);
    this.flour += 2.5 * (size / 10);
    this.butter += 0.5 * (size / 10);
    this.milk += 1;
  }

  public void Bake() {

    System.out.println("You will need " + eggs + " Eggs");
    System.out.printf("You will need %.2f Cups of Flour\n", flour);
    System.out.printf("You will need %.2f Cups of CocoaPowder\n", cocoaPowder);
    System.out.println("You will need " + milk + " Cups of Milk");
    System.out.printf("You will need %.2fg of Butter\n", butter);
    System.out.printf("You will need %.2f teaspoon of Vanilla\n", vanilla);
    System.out.printf("You will need %.2f teaspoon of Salt\n", salt);
    System.out.printf("You will need %.2f teaspoon of Baking Soda\n", bakingSoda);
    System.out.printf("You will need %.2f Cups of Food Coloring", foodColoring);
  }




  public static void main(String[] args) {
    testCake cake = new testCake();
    cake.createTier();
    // cake.createDecorations(); 
    // ... 
    cake.Bake();


    // ************** // 
    // Rendering Code  
    // ************** // 

    Display.createDisplay();

    Loader loader = new Loader();
    Shader shader = new Shader();
    Renderer renderer = new Renderer(shader);


    RawModel model = ModelLoader.loadModel("chocCake", loader);


    MTexture texture = new MTexture(loader.loadTex("choc"));
    TModel tModel = new TModel(model, texture);

    Entity e = new Entity(tModel, new Vector3f(0, 0, -10), 0, 0, 0, 1);

    Entity defaultLook = new Entity(tModel, new Vector3f(0, 0, -10), 0, 0, 0, 1);
    Cam camera = new Cam(defaultLook);

    while (!(org.lwjgl.opengl.Display.isCloseRequested())) {
      camera.move();
      renderer.prepare();
      shader.start();
      shader.loadViewMatrix(camera);
      renderer.render(e, shader);
      shader.stop();
      Display.updateDisplay();
    }

    shader.clean();
    loader.cleanUp();
    Display.closeDisplay();
  }
}
