package CM.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x302ba9749330456cL, 0x8ab141e68cf0c655L, 0x36b8de809fd6d90eL, "CM.structure.Cake"))) {
        return Collections.<ConceptEditor>singletonList(new Cake_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x302ba9749330456cL, 0x8ab141e68cf0c655L, 0x36b8de809fd6d968L, "CM.structure.Circle"))) {
        return Collections.<ConceptEditor>singletonList(new Circle_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x302ba9749330456cL, 0x8ab141e68cf0c655L, 0x36b8de809fd6d986L, "CM.structure.Square"))) {
        return Collections.<ConceptEditor>singletonList(new Square_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x302ba9749330456cL, 0x8ab141e68cf0c655L, 0x36b8de809fd6d930L, "CM.structure.Tier"))) {
        return Collections.<ConceptEditor>singletonList(new Tier_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
