package CM.test;

/*Generated by MPS */

import org.lwjgl.util.vector.Vector3f;

public class Entity {

  private TModel model;
  private Vector3f pos;
  private float rotX;
  private float rotY;
  private float rotZ;
  private float scale;

  public Entity(TModel model, Vector3f pos, float rotx, float roty, float rotz, float scale) {
    this.model = model;
    this.pos = pos;
    this.rotX = rotx;
    this.rotY = roty;
    this.rotZ = rotz;
    this.scale = scale;
  }

  public Vector3f getPos() {
    return this.pos;
  }

  public float getRotX() {
    return this.rotX;
  }

  public float getRotY() {
    return this.rotY;
  }

  public float getRotZ() {
    return this.rotZ;
  }

  public float getScale() {
    return this.scale;
  }

  public TModel getModel() {
    return this.model;
  }

  public void increaseRotation(float dx, float dy, float dz) {
    this.rotX += dx;
    this.rotY += dy;
    this.rotZ += dz;
  }

  public void increasePosition(float dx, float dy, float dz) {
    this.pos.x += dx;
    this.pos.y += dy;
    this.pos.z += dz;
  }
}
