package CM.test;

/*Generated by MPS */


public class MTexture {

  private int textureID;

  public MTexture(int id) {
    this.textureID = id;
  }

  public int getId() {
    return this.textureID;
  }
}
