package CM.test;

/*Generated by MPS */


public class RawModel {

  private int vertexCount;
  private int vaoID;

  public RawModel(int vaoID, int vertexCount) {
    this.vaoID = vaoID;
    this.vertexCount = vertexCount;
  }

  public int getVaoID() {
    return vaoID;
  }

  public int getVertexCount() {
    return vertexCount;
  }


}
