package CM.test;

/*Generated by MPS */


public class TModel {

  private RawModel rawM;
  private MTexture tex;

  public TModel(RawModel m, MTexture t) {
    this.rawM = m;
    this.tex = t;
  }

  public RawModel getRawModel() {
    return this.rawM;
  }

  public MTexture getTexture() {
    return this.tex;
  }
}
