package CM.behavior;

/*Generated by MPS */


/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class Circle_BehaviorDescriptor extends Shape_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "CM.structure.Circle";
  }

}
